export const LANGUAGES = [
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'fr', label: 'French', nativeLabel: 'Français' },
  { code: 'ko', label: 'Korean', nativeLabel: '한국어' },
] as const;

export type LanguageCode = (typeof LANGUAGES)[number]['code'];

export const DEFAULT_LANGUAGE: LanguageCode = 'en';

export const UI_STRINGS: Record<LanguageCode, Record<string, string>> = {
  en: {
    home: 'Home',
    guides: 'Guides',
    map: 'Map',
    saved: 'Saved',
    profile: 'Profile',
    search: 'Search...',
    announcements: 'Announcements',
    latestAnnouncements: 'Latest Announcements',
    quickAccess: 'Quick Access',
    welcome: 'Welcome to',
    campusName: 'Keimyung University',
    noResults: 'No results found',
    noSaved: 'No saved items yet',
    saveHint: 'Tap the bookmark icon on any guide or announcement to save it here.',
    loading: 'Loading...',
    error: 'Something went wrong',
    retry: 'Retry',
    publish: 'Publish',
    unpublish: 'Unpublish',
    delete: 'Delete',
    edit: 'Edit',
    create: 'Create',
    save: 'Save',
    cancel: 'Cancel',
    title: 'Title',
    body: 'Body',
    category: 'Category',
    audience: 'Audience',
    language: 'Language',
    status: 'Status',
    draft: 'Draft',
    published: 'Published',
    admin: 'Admin',
    dashboard: 'Dashboard',
    manageContent: 'Manage Content',
    createAnnouncement: 'Create Announcement',
    createGuide: 'Create Guide',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    email: 'Email',
    password: 'Password',
    allCategories: 'All',
    relatedGuides: 'Related Guides',
    lastUpdated: 'Last updated',
    buildings: 'Buildings',
    seeAll: 'See All',
    summary: 'Summary',
    settings: 'Settings',
    languagePreference: 'Language',
    campus: 'Campus',
    studentStatus: 'Student Status',
  },
  fr: {
    home: 'Accueil',
    guides: 'Guides',
    map: 'Plan',
    saved: 'Favoris',
    profile: 'Profil',
    search: 'Rechercher...',
    announcements: 'Annonces',
    latestAnnouncements: 'Dernières annonces',
    quickAccess: 'Accès rapide',
    welcome: 'Bienvenue à',
    campusName: 'Keimyung University',
    noResults: 'Aucun résultat',
    noSaved: 'Aucun favori',
    saveHint: 'Appuyez sur l\'icône marque-page pour sauvegarder un contenu ici.',
    loading: 'Chargement...',
    error: 'Une erreur est survenue',
    retry: 'Réessayer',
    publish: 'Publier',
    unpublish: 'Dépublier',
    delete: 'Supprimer',
    edit: 'Modifier',
    create: 'Créer',
    save: 'Enregistrer',
    cancel: 'Annuler',
    title: 'Titre',
    body: 'Contenu',
    category: 'Catégorie',
    audience: 'Public',
    language: 'Langue',
    status: 'Statut',
    draft: 'Brouillon',
    published: 'Publié',
    admin: 'Admin',
    dashboard: 'Tableau de bord',
    manageContent: 'Gérer le contenu',
    createAnnouncement: 'Créer une annonce',
    createGuide: 'Créer un guide',
    signIn: 'Connexion',
    signOut: 'Déconnexion',
    email: 'Email',
    password: 'Mot de passe',
    allCategories: 'Tout',
    relatedGuides: 'Guides associés',
    lastUpdated: 'Dernière mise à jour',
    buildings: 'Bâtiments',
    seeAll: 'Voir tout',
    summary: 'Résumé',
    settings: 'Paramètres',
    languagePreference: 'Langue',
    campus: 'Campus',
    studentStatus: 'Statut étudiant',
  },
  ko: {
    home: '홈',
    guides: '가이드',
    map: '지도',
    saved: '저장됨',
    profile: '프로필',
    search: '검색...',
    announcements: '공지사항',
    latestAnnouncements: '최신 공지사항',
    quickAccess: '바로가기',
    welcome: '환영합니다',
    campusName: '계명대학교',
    noResults: '결과 없음',
    noSaved: '저장된 항목 없음',
    saveHint: '가이드나 공지에서 북마크 아이콘을 눌러 여기에 저장하세요.',
    loading: '로딩 중...',
    error: '문제가 발생했습니다',
    retry: '재시도',
    publish: '게시',
    unpublish: '비게시',
    delete: '삭제',
    edit: '편집',
    create: '생성',
    save: '저장',
    cancel: '취소',
    title: '제목',
    body: '본문',
    category: '카테고리',
    audience: '대상',
    language: '언어',
    status: '상태',
    draft: '초안',
    published: '게시됨',
    admin: '관리자',
    dashboard: '대시보드',
    manageContent: '콘텐츠 관리',
    createAnnouncement: '공지 작성',
    createGuide: '가이드 작성',
    signIn: '로그인',
    signOut: '로그아웃',
    email: '이메일',
    password: '비밀번호',
    allCategories: '전체',
    relatedGuides: '관련 가이드',
    lastUpdated: '최종 수정',
    buildings: '건물',
    seeAll: '전체 보기',
    summary: '요약',
    settings: '설정',
    languagePreference: '언어',
    campus: '캠퍼스',
    studentStatus: '학생 상태',
  },
};
